### ISSUE TITLE
1.3.0 Crash

### ISSUE THREAD

**Issue by Invadermonky** [Invadermonky/MagicultureIntegrations#1]
Crash with Flux Lens when Botania installed and Thaumcraft not installed.

Fixed in dev hotfix version 1.3.1. (Not yet released)

**Comment by roidrole** [comment]
If other people experience this crash before new version is released, disabling the new Botania flowers fixes it

**Comment by Invadermonky** [comment]
Fixed as of version [1.12.2-1.3.1](https://www.curseforge.com/minecraft/mc-mods/magiculture-integrations/files/5691003)
