### ISSUE TITLE
[Feature Request] Add Experiment 115 + Kekimurus compat

### ISSUE THREAD

**Issue by Krutoy242** [Invadermonky/MagicultureIntegrations#3]
Twilight Forest have self-regenerating cake called "Experiment 115". It would be nice and cool if Botania cake-eating flower Kekimurus would be able to eat that.

![image](https://github.com/user-attachments/assets/ba301ffe-35ea-4e0b-8e55-6cc5a2ceffb8)

**Comment by Invadermonky** [comment]
I can add this but It will have to wait until the mixin rewrite.

**Comment by Invadermonky** [comment]
[Version 1.12.2-2.0.0](https://www.curseforge.com/minecraft/mc-mods/magiculture-integrations/files/5807502) released. Integration has been added.

**Comment by Krutoy242** [comment]
Tested and its working! The feature of not eating cake completely is nice one. (I wish arcane cake have this feature too).
