### ISSUE TITLE
World crash: `ConcurrentModificationException: magicultureintegrations.events.CommonEventHandler.onWorldTick`

### ISSUE THREAD

**Issue by Krutoy242** [Invadermonky/MagicultureIntegrations#4]
Joining old world after installing MagicultureIntegration and flying around causing crash:
```ruby
Description: Exception in server tick loop

java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
    at java.util.ArrayList$Itr.next(Unknown Source)
    at com.invadermonky.magicultureintegrations.events.CommonEventHandler.onWorldTick(CommonEventHandler.java:40)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1373_CommonEventHandler_onWorldTick_WorldTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:92)
    at com.github.terminatornl.laggoggles.tickcentral.EventBusTransformer.redirectEvent(EventBusTransformer.java:67)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
```

 Rejoining this world repeatedly causing same crashes.

[debug.log](https://github.com/user-attachments/files/16962280/debug.log)

**Comment by Invadermonky** [comment]
This crash is a result of the way I had to handle the tile entities in the first versions of the mod. It's not great and has way too much  overhead so I'm planning on rewriting the integrations using a mixin implementation.

**Comment by Krutoy242** [comment]
Fix still would be appreciated! Still waiting for it to add mod into E2EE.

**Comment by Invadermonky** [comment]
Dealing with a family emergency for the past couple weeks and I haven't had time to work on anything.

Did the [mixin version](https://github.com/Invadermonky/MagicultureIntegrations/issues/2#issuecomment-2360404008) of the mod fix this crash or did it persist?

It should have fixed the crash since the mod no longer uses the `WorldTickEvent` to find tile entities and instead adds the IHeatable/IBoostable interfaces directly to the tile entity classes.

**Comment by Krutoy242** [comment]
> Did the https://github.com/Invadermonky/MagicultureIntegrations/issues/2#issuecomment-2360404008 of the mod fix this crash or did it persist?

I will try and test it later.

**Comment by Invadermonky** [comment]
Have you had time to test the new version?

**Comment by Krutoy242** [comment]
I installed mod and it loaded fine, but i didnt tested functionality yet.

**Comment by Invadermonky** [comment]
Sounds good. I'm planning to try to get the new release out by next weekend.

**Comment by Krutoy242** [comment]
It feels like mod not working or im duing something wrong.
![image](https://github.com/user-attachments/assets/a59639d7-69bc-40e6-8a36-3976c02d21ac)

I found this line in `debug.log` file: 
```ruby
[14:53:53] [Client thread/INFO] [FML]: FML has found a non-mod file magicultureintegrations-1.12.2-2.0.0.jar in your mods directory. It will now be injected into your classpath. This could severe stability issues, it should be removed if possible.
```

There is no Magiculture Integration in mod list and features such as Foxhond+Bellows not working
![image](https://github.com/user-attachments/assets/48354c72-eb94-4f16-b912-9c5cc089982b)

[debug.log](https://github.com/user-attachments/files/17278527/debug.log)

**Comment by Invadermonky** [comment]
That is very strange. Here is the release build (sources included).  Be sure to regenerate the configuration file as a lot of stuff has changed in the 2.0.0 version.

[magicultureintegrations-1.12.2-2.0.0.zip](https://github.com/user-attachments/files/17282023/magicultureintegrations-1.12.2-2.0.0.zip)

**Comment by Krutoy242** [comment]
Ok, it comes out the .zip file is not the .jar, but it contain jars.

**Comment by Krutoy242** [comment]
Tested - mod is loaded, but seems like features not working - TC bellows and Foxhound not speeding up the MA furnaces.

**Comment by Krutoy242** [comment]
Update: Changing default value for fox seems like made it actually working. The default value was 1 and its kinda strange, because it should be at least same as vanilla quark's `3`.

**Comment by Invadermonky** [comment]
There appears to be an issue with the mixins loading correctly for some of the heaters. Working on it now.

>The default value was 1 and its kinda strange, because it should be at least same as vanilla quark's 3.

Quark is actually 1 tick boost every 3 ticks.
```java
if (cookTime > 0 && cookTime % 3 == 0) {
    List<EntityFoxhound> foxhounds = this.world.getEntitiesWithinAABB(EntityFoxhound.class, new AxisAlignedBB(this.getPosition()), (fox) -> {
        return fox != null && fox.isTamed();
    });
    if (!foxhounds.isEmpty() && foxhounds.get(0) == this) {
        ((TileEntityFurnace)tile).setField(2, Math.min(199, cookTime + 1));
    }
}
```

**Comment by Invadermonky** [comment]
Newest version. Fixed Arcane Bellows mixin and a couple of others. Kekimurus Experiment 115 mixin also included and tested.

[magicultureintegrations-1.12.2-2.0.0.zip](https://github.com/user-attachments/files/17335007/magicultureintegrations-1.12.2-2.0.0.zip)

Release is still planned for this weekend.

**Comment by Invadermonky** [comment]
[Version 1.12.2-2.0.0](https://www.curseforge.com/minecraft/mc-mods/magiculture-integrations/files/5807502) released. Issue should be resolved.

**Comment by Krutoy242** [comment]
Flying on same place wont causing crash anymore, issue is fixed!
