### ISSUE TITLE
[Feature Request] Twilight Forest's `Sorting Tree` integration

### ISSUE THREAD

**Issue by Krutoy242** [Invadermonky/MagicultureIntegrations#5]
Most of Twilight Forest unique mechanic are awesome, but lack of integrations, what makes TF one of the most underrated mods in big modpacks like E2E.
Adding more connections would help to give second life to such old mod.

**Sorting Tree** should be able to sort any common inventories, not only vanilla chests. If this is impossible, at least list of valid containers should be provided, like Rustic's Cabinets or Actually Addition's "Small" Storage Crates.

![image](https://github.com/user-attachments/assets/52c1cc4d-eab3-4ae0-978c-19ffdc862161)

**Comment by Invadermonky** [comment]
While I can potentially add this, it might be better to ask for this feature at [The Twilight Forest - Deforestation Edition](https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest-deforestation-edition). The project states that it is still active so you might want to test your luck there.

**Comment by Invadermonky** [comment]
Closing this issue as this feature has been added to [The Twilight Forest - Deforestation Edition](https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest-deforestation-edition) as of [this commit](https://github.com/CaliforniaDemise/twilightforest/commit/b871b955b4bf6a14f856f70e508712ffa18943a9).
