### ISSUE TITLE
Crash with Planar Artifice: Continuation

### ISSUE THREAD

**Issue by Margatroidu** [Invadermonky/MagicultureIntegrations#7]
Crash with [Planar Artifice: Continuation](https://www.curseforge.com/minecraft/mc-mods/planar-artifice)

[crash-2024-10-25_09.56.38-client.txt](https://github.com/user-attachments/files/17517671/crash-2024-10-25_09.56.38-client.txt)

**Comment by Invadermonky** [comment]
Nothing about this crash log has anything to do with Magiculture Integrations and the Magiculture Integrations doesn't touch any of the classes involved in the crash.

**Comment by Margatroidu** [comment]
> Nothing about this crash log has anything to do with Magiculture Integrations and the Magiculture Integrations doesn't touch any of the classes involved in the crash.

Sorry, I got the mods mixed up. The crash is caused by Just Enough Magiculture.
